version: "3.6"

services:
  votingapp:
    image: paulopez/votingapp
    build:
      dockerfile: ./VotingApp.Api/Dockerfile
      context: .
    ports:
      - "8080:80"
    environment:
      REDIS: redisapp:6379
  
  redisapp:
    image: redis
  
  votingapp-test:
    image: votingapp-test
    build:
      context: ./tests
    environment:
      API_URL: http://votingapp/api/voting

    
  
    


    
