apiVersion: v1
kind: Service
metadata:
  labels:
    run: database
  name: database
  namespace: default
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: database
