apiVersion: v1
kind: Service
metadata:
  labels:
    run: votingapp
  name: votingapp
  namespace: default
spec:
  ports:
  - nodePort: 30183
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: votingapp
  type: NodePort
